server.port=8080
spring.application.name=user-service

# Railway MySQL Public URL
spring.datasource.url=jdbc:mysql://tramway.proxy.rlwy.net:33405/railway
spring.datasource.username=root
spring.datasource.password=zGPyuqhFkyCvmFRKWkPuWHTiuSMLpfGX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000